import type { Metadata } from 'next';
import { Raleway, Poppins } from 'next/font/google';

import '../styles/style.scss';
import DataProvider from '@/providers/DataProvider';
import AuthProvider from '@/providers/AuthProvider';
import ToastProvider from '@/providers/ToastProvider';
import { getProfileData } from '@/modules/Admin/services/profile';
import Header from '@/modules/core/components/Header';

// const inter = Inter({ subsets: ["latin"] });

const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '400', '600', '800'],
  style: ['normal', 'italic'],
  variable: '--font-raleway',
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '400', '600', '800'],
  style: ['normal', 'italic'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const profileData = await getProfileData();
  console.log('🚀 ~ profileData:', profileData);

  return (
    <html lang="en" className={`${raleway.variable} ${poppins.variable} dark`}>
      <body>
        <AuthProvider data={profileData || {}}>
          <ToastProvider />
          <DataProvider>
            <Header />
            {children}
          </DataProvider>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
